"""Initial migration

Revision ID: 79df8457dc3b
Revises: a4f1bdcd219a
Create Date: 2025-12-04 01:30:22.468606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79df8457dc3b'
down_revision = 'a4f1bdcd219a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

